apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-31
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-31
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-32
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-32
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-33
    from:
      kind: DockerImage
      name: quay.io/monkey-the-user/iot-anomaly-detection:0.3.2-33
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-34
    from:
      kind: DockerImage
      name: quay.io/monkey-the-user/iot-anomaly-detection:0.3.2-34
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-35
    from:
      kind: DockerImage
      name: quay.io/monkey-the-user/iot-anomaly-detection:0.3.2-35
    importPolicy: {}
    referencePolicy:
      type: Local
