apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-43
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-43
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-45
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-45
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-47
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-47
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-49
    from:
      kind: DockerImage
      name: quay.io/monkey-the-user/iot-consumer:0.3.2-49
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-46
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-46
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-48
    from:
      kind: DockerImage
      name: quay.io/monkey-the-user/iot-consumer:0.3.2-48
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-51
    from:
      kind: DockerImage
      name: quay.io/monkey-the-user/iot-consumer:0.3.2-51
    importPolicy: {}
    referencePolicy:
      type: Local
